### ISSUE TITLE
f

### ISSUE THREAD

**Issue by root-Manas** [xcapri/xcapri#1]

**Comment by root-Manas** [comment]
Hi, please respond to the above message. I am still waiting on your response.

**Comment by xcapri** [comment]
![image](https://github.com/xcapri/xcapri/assets/43540712/9f565fd5-0e37-498d-8ab6-4414777ca5e2)

If this is you, I have replied to your email.

**Comment by root-Manas** [comment]
Oh well bad luck I guess. Thanks for your response please do consider
updating the nuclei template. Thanks.

**Comment by root-Manas** [comment]
Thanks. Replied to the email. Closing this issue.
